create table role
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

INSERT INTO role(name)
values ('ROLE_ADMIN'),
       ('ROLE_STUDENT'),
       ('ROLE_TEACHER');
